version: '3.2'

services:
    forumple:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: forumple:latest
        container_name: forumple
        env_file:
            - .env
        ports:
            - 3000:3000
        restart: unless-stopped
